SUCCESS_STATUS_CODE = 200
FAIL_STATUS_CODE = 500
NOT_FOUND = 404
ACCESS_TOKEN_ERROR_CODE = 1001
NOT_AUTHORIZED_ERROR_CODE = 1003
PARAMETER_MISSING_CODE = 2001
PARAMETER_VALIDATION = 2002
PERMISSION_ERROR_CODE = 3001
EMAIL_NOT_VERIFIED_ERROR_CODE = 3002
EMAIL_ALREADY_VERIFIED_CODE = 3003
METHOD_NOT_ALLOWED_CODE = 405
USER_NOT_REGISTERED_CODE = 1002
INVALID_INPUT_ERROR_CODE = 4001
UNABLE_TO_CREATE_USER_CODE = 5001
ALREADY_EXIST_ERROR_CODE = 5002


ACCESS_TOKEN_MISSING_MESSAGE = 'Access Token is Missing!'
ACCESS_TOKEN_WRONG_MESSAGE = 'Access Token is Wrong!'
ACCESS_TOKEN_EXPIRED_MESSAGE = 'Session Expired! Please login again!'
PARAMETER_MISSING_MESSAGE = 'Required Parameters Missing!'
PARAMETER_MISSING_OR_INVALID_MESSAGE = 'Required Parameters Missing or Invalid!'
PERMISSION_ERROR_MESSAGE = "You're not Authorized!"
USER_NOT_REGISTERED_MESSAGE = "You're not registered!"
USER_NOT_FOUND = 'User not found!'
METHOD_NOT_ALLOWED_MESSAGE = "This method not allowed!"

AVOID_AUTHENTICATION = (
    ('/admin/'),
    ('/auth/'),
    ('/docs/'),
    ('/docs-swagger/')
)